package armrobot.model;

// WEEK 6: Cube extends ObjectItem (superclass)
// Cube inherits id, name, shape from ObjectItem
// Cube adds its own special method: stack()
public class Cube extends ObjectItem {

    // ---- Constructor ----

    public Cube(String name) {
        super(name, "Cube");
    }

    // ---- Special method for Cube only ----

    public void stack() {
        System.out.println(name + " can be stacked on other cubes.");
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public String toString() {
        return "Cube{} " + super.toString();
    }
}
