package armrobot.model;

// WEEK 6: Engineer extends User (superclass)
// Engineer inherits id, name, role from User
// Engineer adds its own special method: operateRobot()
public class Engineer extends User {

    // ---- Constructor ----

    public Engineer(String name) {
        super(name, "Engineer");
    }

    // ---- Special method for Engineer only ----

    public void operateRobot() {
        System.out.println(name + " is operating the robot arm.");
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public String toString() {
        return "Engineer{} " + super.toString();
    }
}
