package armrobot.model;

// WEEK 6: Manager extends User (superclass)
// Manager inherits id, name, role from User
// Manager adds its own special method: supervise()
public class Manager extends User {

    // ---- Constructor ----

    public Manager(String name) {
        super(name, "Manager");
    }

    // ---- Special method for Manager only ----

    public void supervise() {
        System.out.println(name + " is supervising the robot operation.");
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public String toString() {
        return "Manager{} " + super.toString();
    }
}
