package armrobot.model;

// WEEK 6: Sphere extends ObjectItem (superclass)
// Sphere inherits id, name, shape from ObjectItem
// Sphere adds its own special method: roll()
public class Sphere extends ObjectItem {

    // ---- Constructor ----

    public Sphere(String name) {
        super(name, "Sphere");
    }

    // ---- Special method for Sphere only ----

    public void roll() {
        System.out.println(name + " can roll across the surface.");
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        if (!super.equals(o)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public String toString() {
        return "Sphere{} " + super.toString();
    }
}
