package armrobot.model;

import armrobot.interfaces.Displayable;

import java.util.Objects;

public class ObjectItem implements Displayable {

    // static counter -- shared across all ObjectItem objects
    private static int itemCount = 0;

    private int    id;
    private String name;
    private String shape; // only "Cube" or "Sphere"

    // ---- Constructor ----

    public ObjectItem(String name, String shape) {
        this.id = ++itemCount;
        setName(name);
        setShape(shape);
    }

    // ---- Displayable ----

    @Override
    public void displayInfo() {
        System.out.println("ObjectItem [id=" + id + ", name=" + name + ", shape=" + shape + "]");
    }

    // ---- Getters (generated) ----

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getShape() {
        return shape;
    }

    public static int getItemCount() {
        return itemCount;
    }

    // ---- Setters with validation ----

    public void setName(String name) {
        if (name == null || name.isBlank()) {
            this.name = "Unknown";
        } else {
            this.name = name;
        }
    }

    public void setShape(String shape) {
        if (shape != null &&
                (shape.equalsIgnoreCase("Cube") || shape.equalsIgnoreCase("Sphere"))) {
            this.shape = shape;
        } else {
            System.out.println("Warning: shape must be Cube or Sphere. Set to Unknown.");
            this.shape = "Unknown";
        }
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ObjectItem that = (ObjectItem) o;
        return id == that.id &&
                Objects.equals(name, that.name) &&
                Objects.equals(shape, that.shape);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, shape);
    }

    @Override
    public String toString() {
        return "ObjectItem{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", shape='" + shape + '\'' +
                '}';
    }
}
