package armrobot.model;

import armrobot.interfaces.Controllable;
import armrobot.interfaces.Displayable;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

public class RobotArm implements Controllable, Displayable {

    // static counter -- shared across all RobotArm objects
    private static int robotCount = 0;

    private int    id;
    private String robotName;
    private int    posX;
    private int    posY;
    private boolean isHolding;

    // composition -- RobotArm holds an ObjectItem
    private ObjectItem heldItem;

    // ArrayList -- ordered move log, duplicates allowed
    private ArrayList<String> moveHistory = new ArrayList<>();

    // Set -- unique positions only, no duplicates
    private Set<String> visitedPositions = new HashSet<>();

    // Map -- counts how many times each position was visited
    private Map<String, Integer> positionLog = new HashMap<>();

    // ---- Constructor ----

    public RobotArm(String robotName) {
        this.id        = ++robotCount;
        this.robotName = robotName;
        this.posX      = 0;
        this.posY      = 0;
        this.isHolding = false;
        this.heldItem  = null;
        logPosition(0, 0);
    }

    // ---- Controllable ----

    @Override
    public void moveTo(int x, int y) {
        this.posX = x;
        this.posY = y;
        String move = "Moved to (" + x + "," + y + ")";
        moveHistory.add(move);
        logPosition(x, y);
        System.out.println("  " + robotName + " -> " + move);
    }

    @Override
    public void drop() {
        if (isHolding && heldItem != null) {
            System.out.println("  " + robotName + " dropped: " + heldItem.getName()
                    + " at (" + posX + "," + posY + ")");
            heldItem  = null;
            isHolding = false;
        } else {
            System.out.println("  " + robotName + " has nothing to drop.");
        }
    }

    @Override
    public void returnHome() {
        moveTo(0, 0);
        System.out.println("  " + robotName + " returned home.");
    }

    @Override
    public String getStatus() {
        String holding = isHolding ? heldItem.getName() : "nothing";
        return robotName + " | Position: (" + posX + "," + posY + ")"
                + " | Holding: " + holding;
    }

    // ---- Displayable ----

    @Override
    public void displayInfo() {
        System.out.println("RobotArm [id=" + id
                + ", name=" + robotName
                + ", position=(" + posX + "," + posY + ")"
                + ", holding=" + isHolding + "]");
    }

    // ---- Custom logic ----

    public boolean pick(ObjectItem item) {
        if (item == null) {
            System.out.println("  No item to pick.");
            returnHome();
            return false;
        }
        if (!item.getShape().equalsIgnoreCase("Cube")) {
            System.out.println("  PICK FAILED: " + item.getName()
                    + " is a " + item.getShape()
                    + ". Robot can only pick Cubes.");
            returnHome();
            return false;
        }
        this.heldItem  = item;
        this.isHolding = true;
        System.out.println("  PICK SUCCESS: " + item.getName()
                + " (" + item.getShape() + ") picked up.");
        return true;
    }

    private void logPosition(int x, int y) {
        String key = "(" + x + "," + y + ")";
        visitedPositions.add(key);
        positionLog.put(key, positionLog.getOrDefault(key, 0) + 1);
    }

    public void printMoveHistory() {
        System.out.println("  Move History (ArrayList, in order):");
        for (String m : moveHistory) {
            System.out.println("    - " + m);
        }
    }

    public void printVisitedPositions() {
        System.out.println("  Unique Positions Visited (Set, no duplicates):");
        for (String pos : visitedPositions) {
            System.out.println("    - " + pos);
        }
    }

    public void printPositionLog() {
        System.out.println("  Position Visit Count (Map, key=position, value=count):");
        for (Map.Entry<String, Integer> entry : positionLog.entrySet()) {
            System.out.println("    - " + entry.getKey()
                    + " visited " + entry.getValue() + " time(s)");
        }
    }

    // ---- Getters (generated) ----

    public int getId() {
        return id;
    }

    public String getRobotName() {
        return robotName;
    }

    public int getPosX() {
        return posX;
    }

    public int getPosY() {
        return posY;
    }

    public boolean isHolding() {
        return isHolding;
    }

    public ObjectItem getHeldItem() {
        return heldItem;
    }

    public static int getRobotCount() {
        return robotCount;
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        RobotArm robotArm = (RobotArm) o;
        return id == robotArm.id &&
                Objects.equals(robotName, robotArm.robotName);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, robotName);
    }

    @Override
    public String toString() {
        return "RobotArm{" +
                "id=" + id +
                ", robotName='" + robotName + '\'' +
                ", posX=" + posX +
                ", posY=" + posY +
                ", isHolding=" + isHolding +
                '}';
    }
}
