package armrobot.model;

import armrobot.interfaces.Displayable;

import java.util.Objects;

public class User implements Displayable {

    // static counter -- shared across all User objects
    private static int userCount = 0;

    private int    id;
    private String name;
    private String role;

    // ---- Constructor ----

    public User(String name, String role) {
        this.id = ++userCount;
        setName(name);
        setRole(role);
    }

    // ---- Displayable ----

    @Override
    public void displayInfo() {
        System.out.println("User [id=" + id + ", name=" + name + ", role=" + role + "]");
    }

    // ---- Getters (generated) ----

    public int getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getRole() {
        return role;
    }

    public static int getUserCount() {
        return userCount;
    }

    // ---- Setters with validation ----

    public void setName(String name) {
        if (name == null || name.isBlank()) {
            this.name = "Unknown";
        } else {
            this.name = name;
        }
    }

    public void setRole(String role) {
        if (role == null || role.isBlank()) {
            this.role = "None";
        } else {
            this.role = role;
        }
    }

    // ---- Generated by IntelliJ IDEA ----

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        User user = (User) o;
        return id == user.id &&
                Objects.equals(name, user.name) &&
                Objects.equals(role, user.role);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, name, role);
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", role='" + role + '\'' +
                '}';
    }
}
